### ISSUE TITLE
Deno Deploy runtime error

### ISSUE THREAD

**Issue by SubZtep** [LeonskiDev/chalkin#1]
Hi, adding my script with **chalkin** to [Deno Deploy](https://deno.com/deploy) works, but when I try to access it, the page is unavailable _(502 Bad Gateway)_ and log this error:

```
EvalError: Code generation from strings disallowed for this context
    at new Function (<anonymous>)
    at new Chalkin (https://deno.land/x/chalkin@v0.1.2/mod.ts:15:9)
    at https://deno.land/x/chalkin@v0.1.2/mod.ts:43:16
```

I could reproduce easily by linking this simple script:
https://github.com/SubZtep/deno-literate-meme/blob/ada3816289800b73e72cfed5409b74397f4c7769/chalkin-test.js

Cheers!

**Comment by LeonskiDev** [comment]
Sorry for the long reply. I think I know what the issue is, I'll add a note to the fix and leave a message here on how to *hopefully* fix it.

**Comment by LeonskiDev** [comment]
If you check out the latest release you should be able to use the information in that to fix the issue you're having.

Release: https://github.com/LeonskiDev/chalkin/releases/tag/v0.1.3

**Comment by SubZtep** [comment]
Thanks for the update! Figured out, this is a server issue, the `Function` constructor is disabled due `eval` call.
Closing the ticket, the script works as expected.

---

I made a quick workaround to solve this issue:

```js
const chalkin = Deno.env.get("DENO_DEPLOYMENT_ID") === undefined
  ? (await import("https://deno.land/x/chalkin@v0.1.3/mod.ts")).default
  : new Proxy({}, {
    get() {
      return new Proxy(Function.prototype, this)
    }
  })
```
